### ISSUE TITLE
add to stackage ?

### ISSUE THREAD

**Issue by simonmichael** [aaronallen8455/breakpoint#1]
breakpoint worked nicely for me (except the interactivity didn't work well when debugging a brick app, but that's to be expected). Thank you!

Could it be [added to stackage](https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml) ?

**Comment by aaronallen8455** [comment]
I saw that it has been added to stackage as part of an `hledger` update so I'll go ahead and close this issue. As for working with a brick app, I've considered the possibility of having the plugin talk to a web GUI via sockets, perhaps I'll put some more thought into that. Thanks!

**Comment by simonmichael** [comment]
Thanks Aaron. Do move the package to your own section in build-constraints.yaml if you'd prefer.
