### ISSUE TITLE
fails to build on windows, GHC.Event not available

### ISSUE THREAD

**Issue by simonmichael** [aaronallen8455/breakpoint#10]
breakpoint imports [GHC.Event](https://hackage.haskell.org/package/base-4.17.0.0/docs/GHC-Event.html), which the haddock describes as "GHC internal", and which in fact is not available on MS Windows.

**Comment by aaronallen8455** [comment]
Thanks for letting me know @simonmichael! This should be easy to fix and I am working on updating my CI workflow to include Windows.

**Comment by aaronallen8455** [comment]
Fixed by d7d38354b9c5200d2ca2d832f903d249dc5bfc3f

**Comment by simonmichael** [comment]
Hooray, thank you !
