### ISSUE TITLE
Relax upper bound on `ansi-terminal` to permit `ansi-terminal-1.1`

### ISSUE THREAD

**Issue by mpilgrem** [aaronallen8455/breakpoint#13]
Motivation: https://github.com/commercialhaskell/stackage/issues/7306

**Comment by simonmichael** [comment]
@aaronallen8455 I confirm that master (36739a1) builds and passes tests with ansi-terminal-1.1.

Related: with GHC 9.8.1 there is one warning:

```
/Users/simon/src/DEVTOOLS/breakpoint/test/Spec.hs:190:10: warning: [GHC-63394] [-Wx-partial]
    In the use of ‘head’
    (imported from Prelude, but defined in GHC.List):
    "This is a partial function, it throws an error on empty lists. Use pattern matching or Data.List.uncons instead. Consider refactoring to use Data.List.NonEmpty."
```

And when you next do a release of breakpoint, would you mind also moving it from my name to yours in https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml ? Thanks!

**Comment by aaronallen8455** [comment]
I've uploaded a new release bumping the `ansi-terminal` bounds and a PR has been opened to change the ownership info in stackage. Thanks!
